# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Use a lighter image for running the app
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the built application code from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# Set environment variable for Apify API Token
ENV APIFY_API_TOKEN=your-apify-api-token

# Specify the command to run the app
ENTRYPOINT ["node", "build/index.js"]
